version: 1
project:
  name: testProject
  version: 1
  modules:
    second_mod: testproject.second_module
    _default: testproject.api_module
  startup:
    - postgres_connect
    - minio_connect
  shutdown:
    - close
  entrypoints:
    - name: ep1
      entrypoint: second_mod.hello_name_and_age
      path: hello/{name}/{age}
    - name: ep2
      entrypoint: second_mod.hello_name
      path: hello/{name}
    - name: ep3
      entrypoint: second_mod.hello_world
      path: "hello"
    - name: ep4
      entrypoint: second_mod.hello_post
      path: hellopost
      methods:
        - POST
        - PUT
    - name: ep5
      entrypoint: _default.hello_pydantic
      path: hellopydantic
      methods:
        - PATCH
    - entrypoint: hello_dynamic
    - name: ep6
      entrypoint: hello_header
      path: helloheader
      headers:
        - name
        - age
    - name: ep7
      entrypoint: insert_user
      path: insert_user
      methods:
        - POST
    - name: ep8
      entrypoint: fetch_users
      path: fetch_users
    - name: ep9
      entrypoint: upload
      path: upload
      methods:
        - POST
    - name: ep10
      entrypoint: download
      path: download
